name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build -- --configuration production --base-href=/wii-news-channel/
        
      - name: Debug build output
        run: |
          echo "Initial directory structure:"
          ls -R docs/
        
      - name: Prepare files
        run: |
          # Create temp directory
          mkdir -p docs/temp
          
          # Show contents before copy
          echo "Contents of docs/browser/browser:"
          ls -la docs/browser/browser || echo "browser directory not found"
          
          # Copy files with verbose output
          cp -rv docs/browser/browser/* docs/temp/ || echo "Copy to temp failed"
          
          # Show temp contents
          echo "Contents of temp:"
          ls -la docs/temp || echo "temp directory empty"
          
          # Clean and move files
          rm -rf docs/browser
          mv docs/temp/* docs/ || echo "Move failed"
          rm -rf docs/temp
          
          # Add required files
          touch docs/.nojekyll
          cp docs/index.html docs/404.html
          echo "Build date: $(date)" > docs/build.txt
          
          # Show final structure
          echo "Final directory structure:"
          ls -R docs/
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          folder: docs
          branch: gh-pages
          clean: true
          clean-exclude: |
            .nojekyll
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Deploy to GitHub Pages [skip ci]"
          force: true 